From dbt2-base

RUN apt-get install -y ghostscript \
                       pandoc \
                       python3-docutils \
                       r-base \
                       texlive-latex-base \
                       texlive-latex-recommended

ARG PGVERSION

ENV PATH="/usr/lib/postgresql/${PGVERSION}/bin:$PATH"

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
RUN make -f Makefile.cmake release
RUN (cd builds/release && make install)
