From dbt2-base

RUN dnf -y install epel-release && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    dnf -y install R

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
RUN make release
RUN (cd builds/release && make install)
