From dbt2-base

ARG PGVERSION

ENV PATH="/usr/lib/postgresql/${PGVERSION}/bin:$PATH"

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
RUN make -f Makefile.cmake release
RUN (cd builds/release && make install)
