From dbt2-base

RUN dnf -y install epel-release && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    dnf -y install R

ARG PGVERSION

ENV PATH="/usr/pgsql-${PGVERSION}/bin:$PATH"

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
# The driver itself is database agnostic, but the build system isn't because
# it's building everything.
ARG dbms=pgsql
ENV DBMS="$dbms"
RUN make release
RUN (cd builds/release && make install)
