From dbt2-base

ARG PGVERSION

ENV PATH="/usr/pgsql-${PGVERSION}/bin:$PATH"
ENV PKG_CONFIG_PATH="/usr/pgsql-${PGVERSION}/lib/pkgconfig"

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
RUN make -f Makefile.cmake release
RUN (cd builds/release && make install)
