From dbt2-base

ARG PGVERSION

ENV PATH="/usr/pgsql-${PGVERSION}/bin:$PATH"

COPY . /usr/local/src/dbt2
WORKDIR /usr/local/src/dbt2
ARG dbms=pgsql
ENV DBMS="$dbms"
RUN make release
RUN (cd builds/release && make install)
