#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright The DBT-2 Authors

dbt2-driver3 \
		-altered 1 \
		-ktd 0 \
		-ktn 0 \
		-kto 0 \
		-ktp 0 \
		-kts 0 \
		-sleep 100 \
		-ttd 0 \
		-ttn 0 \
		-tto 0 \
		-ttp 0 \
		-tts 0 \
		"$@"
