#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2021 Mark Wong
#               2002-2022 Mark Wong
#

if [ -z ${DBT2PGDATA} ]; then
    echo "DBT2PGDATA not defined."
    exit 1
fi

if [ -z ${DBT2DBNAME} ]; then
    echo "DBT2DBNAME not defined."
    exit 1
fi

if [ ! "x$DBT2XLOGDIR" = "x" ]; then
	INITDBFLAGS="-X $DBT2XLOGDIR"
fi

# Initialize the PostgreSQL instance
echo "Initializing database instance..."
if [ -d ${DBT2PGDATA} ]; then
	echo "PGData directory '${DBT2PGDATA}' already exists, skipping initdb..."
else
	initdb -D $DBT2PGDATA  -E UTF8 --locale=en_US.utf8 \
			--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8 $INITDBFLAGS || \
			exit 1
fi
