#!/bin/bash

do_the_load()
{
	local H=$1
	local W=$(( $2 * $RANGE + 1))

#dbt2-pgsql-load-db -w $SCALE_FACTOR -W $W -P $RANGE -D -b
	ssh -x $H << EOF
source dbt2_profile
dbt2-pgsql-load-db -w $SCALE_FACTOR -W $W -P $RANGE -D
EOF
}

load_items()
{
	local H=$1

	ssh -x $H << EOF
source dbt2_profile
dbt2-datagen -w $SCALE_FACTOR --table item --pgsql --direct
EOF
}

while getopts "P:w:" OPT; do
	case ${OPT} in
	P)
		RANGE=$OPTARG
		;;
	w)
		SCALE_FACTOR=$OPTARG
		;;
	esac
done
shift $((OPTIND - 1))

echo $@

C=0
for HOST in $@; do
	echo "loading: $HOST"
	if [ $C -eq 0 ]; then
		#load_items $HOST &
		load_items $HOST
	fi
	#do_the_load $HOST $C &
	do_the_load $HOST $C
	C=$(( $C + 1 ))
done

wait
