#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2005-2006 Open Source Development Labs, Inc.
#               2005-2021 Mark Wong
#

usage()
{
	echo "Usage:"
	echo "    dbt2-pgsql-build-db [options]"
	echo "    dbt2-pgsql-build-db -h"
	echo "Options:"
	echo "    -l <port>"
	echo "        PostgreSQL port"
	echo "    -p <database_parameters>"
	echo "        PostgreSQL database parameters."
	echo "    -r"
	echo "        Drop existing database before building a new database"
	echo "    -s <c | plpgsql>"
	echo "        User defined functions to install, default: c"
	echo "    -t"
	echo "        Use tablespaces."
	echo "    -u"
	echo "        Run as an unprivileged PostgreSQL user."
	echo "    -w <scale factor>"
	echo "        Number of warehouses to build. Default 1."
}

WAREHOUSES=1
GENERATE_DATAFILE=0
PRIVILEGED=1
REBUILD_DB=0
UDF_TYPE="c"
while getopts "hl:p:rs:tuw:" OPT; do
	case ${OPT} in
	h)
		usage
		exit 0
		;;
	l)
		PORT=${OPTARG}
		;;
	p)
		PARAMETERS=$OPTARG
		;;
	r)
		REBUILD_DB=1
		;;
	s)
		UDF_TYPE=$OPTARG
		;;
	t)
		TABLESPACES_FLAG="-t"
		;;
	u)
		PRIVILEGED=0
		;;
	w)
		WAREHOUSES=${OPTARG}
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-l ${PORT}"
fi

if [ $REBUILD_DB -eq 1 ] && [ -d $DBT2PGDATA ]; then
	if [ $PRIVILEGED -eq 1 ]; then
		echo "Restarting the database to reset database parameters..."
		dbt2-pgsql-stop-db
		dbt2-pgsql-start-db -p "${PARAMETERS}" || exit 1
	fi
	dbt2-pgsql-drop-db ${PORTARG}
fi

if [ $PRIVILEGED -eq 1 ]; then
	dbt2-pgsql-init-db ${PORTARG} || exit 1
fi
dbt2-pgsql-create-db ${PORTARG} || exit 1
dbt2-pgsql-create-tables ${PORTARG} ${TABLESPACES_FLAG} || exit 1

SEED=`dbt2-rand 1 18446744073709551615 0`

# FIXME: Make datagen take argument instead of setting environment variables
# for psql.
export PGPORT="${PORT}"
export PGDATABASE="${DBT2DBNAME}"

dbt2-pgsql-load-db $PORTARG -s $SEED -w $WAREHOUSES || exit 1
dbt2-pgsql-create-indexes ${PORTARG} ${TABLESPACES_FLAG} || exit 1
dbt2-pgsql-load-stored-procs $PORTARG -t $UDF_TYPE || exit 1

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi

SEED=`dbt2-rand -1 1 15`
psql ${PORTARG} -e -d ${DBT2DBNAME} -c "SELECT setseed(${SEED});" || exit 1

# VACUUM FULL ANALYZE: Build optimizer statistics for newly-created
# tables. The VACUUM FULL is probably unnecessary; we want to scan the
# heap and update the commit-hint bits on each new tuple, but a regular
# VACUUM ought to suffice for that.

vacuumdb ${PORTARG} -z -f -d ${DBT2DBNAME} || exit 1

exit 0
