#! /bin/sh
#
# This file is released under the terms of the Artistic License.  Please see
# the file LICENSE, included in this package, for details.
#
# Copyright (C) 2010 Sun Microsystems
#

while getopts  "l:w:" OPT; do
	case ${OPT} in
	l)
		PORT_ARG="-l ${OPTARG}"
		;;
	w)
		WORKING_DIR_ARG="-w ${OPTARG}"
		;;
	esac
done

dbt2-drizzle-admin -s stop ${WORKING_DIR_ARG} ${PORT_ARG}
