#! /bin/sh
#
# This file is released under the terms of the Artistic License.  Please see
# the file LICENSE, included in this package, for details.
#
# Copyright (C) 2010 Sun Microsystems
#

while getopts "l:o:p:w:" OPT; do
	case ${OPT} in
	l)
		PORT_ARG="-l ${OPTARG}}"
		;;
	o)
		OUTPUT_ARG="-o \"${OPTARG}\""
		;;
	p)
		PARAMS_ARG="-p \"${OPTARG}\""
		;;
	w)
		WORKING_DIR_ARG="-w ${OPTARG}"
		;;
	esac
done

eval dbt2-drizzle-admin -s start ${WORKING_DIR_ARG} ${PARAMS_ARG} \
		${OUTPUT_ARG} ${PORT_ARG}
