#!/bin/sh

# Build a Docker image with the DBT-2 client installed from the code in the
# local directory.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

DBMS="pgsql"

if [ $# -ge 1 ]; then
	DBMS=$1
fi

TOPDIR=`dirname $0`
${TOPDIR}/prepare-image || exit 1

TOPDIR="${TOPDIR}/.."
docker build -t dbt2-client-${DBMS} -f Dockerfile.client ${TOPDIR}
if [ $? -ne 0 ]; then
        echo "usage: $0 [DBMS]"
        echo
        echo "DBMS options: (default: pgsql)"
        echo "  pgsql"
        exit 1
fi

