#!/bin/sh

# Build a Docker image with the DBT-2 driver installed from the code in the
# local directory.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

PGVERSION=13

which jq > /dev/null 2>&1
if [ $? -eq 0 ]; then
	PGORG="https://www.postgresql.org/versions.json"
	PGVERSION=`curl -s $PGORG | jq -r 'sort | .[].major' | tail -n 1`
fi
echo "Using PostgreSQL Major Version $PGVERSION"

TOPDIR=`dirname $0`
${TOPDIR}/prepare-image || exit 1

TOPDIR="${TOPDIR}/.."
docker build --build-arg PGVERSION=$PGVERSION -t dbt2-driver \
		-f Dockerfile.driver ${TOPDIR}
