#!/bin/sh

# Start the DBT-2 Driver.

usage()
{
	echo "usage: $0 <dbms address> [DBMS [WAREHOUSES [DURATION]]]"
}

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

DOCKER_NAME="dbt2-driver-${WAREHOUSES}w"
DOCKER_TAG="dbt2-driver"
WAREHOUSES=1
# In seconds.
TEST_LENGTH=120

HOST=$1

if [ $# -ge 2 ]; then
	DBMS=$2
fi

if [ $# -ge 3 ]; then
	WAREHOUSES=$3
fi

if [ $# -ge 4 ]; then
	TEST_LENGTH=$4
fi

DOCKERDIR=`dirname $0`

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
docker inspect $DOCKER_TAG > /dev/null
if [ $? -ne 0 ]; then
	${DOCKERDIR}/build-driver || exit 1
fi

if [ "x${DBMS}" = "xcockroach" ]; then
	EXTRA="-l 26257"
	DEXTRA="-e PGCLIENTENCODING=UTF-8 -e PGPORT=26257"
	DBUSER="root"
elif [ "x${DBMS}" = "xpgsql" ]; then
	DBUSER="postgres"
else
	echo "ERROR: unrecognized dbms $DBMS"
	exit 1
fi

docker run --rm --name $DOCKER_NAME -e DRIVER3=1 -e DBT2DBNAME=dbt2 \
		-e PGUSER=$DBUSER -e PGDATABASE=dbt2 -e PGHOST=$HOST $DEXTRA \
		$DOCKER_TAG \
		dbt2-run-workload -a $DBMS -D dbt2 -d $TEST_LENGTH -w $WAREHOUSES -A \
				-H $HOST -n -s 100 -u -y -t 1 -o /tmp/results $EXTRA
if [ $? -ne 0 ]; then
	usage
	exit 1
fi
