#!/bin/sh

# Open a shell on one of the DBT-2 Docker images.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

usage()
{
	echo "usage: `basename $0` dbt2-base"
	echo "usage: `basename $0` dbt2-client <dbms>"
	echo "usage: `basename $0` dbt2-database <dbms> <warehouses>"
	echo "usage: `basename $0` dbt2-driver"
}

DBMS=""
DBT2_TAG=""
DOCKER_TAG=""
SF=""

if [ $# -lt 1 ] || [ $# -gt 3 ]; then
	usage
	exit 1
fi

DBT2_TAG="$1"

if [ $# -eq 1 ]; then
	if [ ! "x$DBT2_TAG" = "xdbt2-base" ] && \
			[ ! "x$DBT2_TAG" = "xdbt2-driver" ]; then
		usage
		exit 1
	fi
	DOCKER_TAG="$DBT2_TAG"
fi

DBMS="$2"
if [ $# -eq 2 ]; then
	if [ ! "x$DBT2_TAG" = "xdbt2-client" ]; then
		usage
		exit 1
	fi
	DOCKER_TAG="${DBT2_TAG}-${DBMS}"
fi

SF="$3"
if [ $# -eq 3 ]; then
	if [ ! "x$DBT2_TAG" = "xdbt2-database" ]; then
		usage
		exit 1
	fi
	DOCKER_TAG="${DBT2_TAG}-${DBMS}-${SF}w"
fi

docker run --rm -i -t ${DOCKER_TAG} /bin/bash
