#!/bin/sh

# Start the DBT-2 client.

usage()
{
	echo "usage: $0 <database address> [DBMS [CONNECTIONS]]"
}

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

DATABASE_CONNECTIONS=10
DBMS="pgsql"

HOST=$1

if [ $# -ge 2 ]; then
	DBMS=$2
fi

if [ $# -ge 3 ]; then
	DATABASE_CONNECTIONS=$3
fi

DOCKERDIR=`dirname $0`
DOCKER_NAME="dbt2-client-${DATABASE_CONNECTIONS}"
DOCKER_TAG="dbt2-client"

DBNAME="dbt2"

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
docker inspect $DOCKER_TAG > /dev/null
if [ $? -ne 0 ]; then
	${DOCKERDIR}/build-client $DBMS || exit 1
fi

if [ "x$DBMS" = "xpgsql" ]; then
	docker run -d --rm --name $DOCKER_NAME -p 30000:30000 \
		-e PGUSER="postgres" \
		$DOCKER_TAG \
		dbt2-client -a $DBMS -f -c $DATABASE_CONNECTIONS -d $HOST -b $DBNAME \
				-o /tmp
	RC=$?
else
	RC=1
fi
if [ $RC -ne 0 ]; then
	usage
	exit 1
fi

which jq > /dev/null 2>&1
if [ $? -eq 0 ]; then
	IPADDRESS=`docker inspect $DOCKER_NAME | jq -r '.[0].NetworkSettings.IPAddress'`
	echo "IP Address: $IPADDRESS"
	echo "${DOCKERDIR}/start-driver $IPADDRESS"
else
	echo "Install jq for some tips the next time you run this script, or"
	echo "read the bottom of the file: $0"
fi
