#!/bin/sh

# Start the DBT-2 PostgreSQL database.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

WAREHOUSES=1
DBMS="pgsql"

if [ $# -ge 1 ]; then
	WAREHOUSES=$1
fi

if [ $# -ge 2 ]; then
	DBMS=$2
fi

DOCKERDIR=`dirname $0`
DOCKER_TAG="dbt2-database-${DBMS}-${WAREHOUSES}w"
DOCKER_NAME="dbt2-database-${DBMS}-${WAREHOUSES}w-0"

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
docker inspect $DOCKER_NAME > /dev/null
if [ $? -ne 0 ]; then
	${DOCKERDIR}/build-database $WAREHOUSES $DBMS || exit 1
fi

if [ "x$DBMS" = "xpgsql" ]; then
	PGDATA="/opt/pgdata"
	docker run -d --rm -u postgres:postgres --name $DOCKER_NAME -p 5432:5432 \
			$DOCKER_TAG postgres -D $PGDATA \
			-c client_encoding='SQL_ASCII' \
			-c listen_addresses='*' \
			-c unix_socket_directories='/tmp'
	RC=$?
else
	RC=1
fi
if [ $RC -ne 0 ]; then
	echo "usage: $0 [WAREHOUSES [DBMS]]"
	echo
	echo "DBMS options: (default: pgsql)"
	echo "  pgsql"
	exit 1
fi

which jq > /dev/null 2>&1
if [ $? -eq 0 ]; then
	IPADDRESS=`docker inspect $DOCKER_NAME | jq -r '.[0].NetworkSettings.IPAddress'`
	echo "IP Address: $IPADDRESS"
	echo "${DOCKERDIR}/start-client $IPADDRESS $DBMS"
	if [ "x$DBMS" = "xpgsql" ]; then
		echo "PGCLIENTENCODING=\"SQL_ASCII\" psql -h $IPADDRESS dbt2 postgres"
	fi
else
	echo "Install jq for some tips the next time you run this script, or"
	echo "read the bottom of the file: $0"
fi
