#!/bin/bash

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2008 Steve VanDeBogart & U.C. Regents
#

# Sqlite is not a daemon

true
